aws:
  region: us-east-1
  accessKeyId: ${AWS_KEY:REPLACEME}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY:REPLACEME}
  s3:
    bucketName: document-bucket
    preSigner:
      expireInMinutes: 1

      
spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
      
springdoc:
  swagger-ui:
    oauth:
      # swagger-ui custom path
      path: /swagger-ui.html
